[theme]
primaryColor = "#ffffff"
backgroundColor = "#1f2228"
secondaryBackgroundColor = "#1A1F2E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
